"use client";

import { useParams } from "next/navigation";
import { useEffect, useState } from "react";
import CaseRouteState from "@/components/cases/CaseRouteState";
import CaseStageShell from "@/components/cases/CaseStageShell";
import { useCase } from "@/hooks/useCase";
import { getRouteParam } from "@/lib/routeParams";
import {
  generateCaseReport,
  resumeCaseReport,
  getLatestCaseReport,
  updateReportReviewStatus,
  downloadReportExport,
} from "@/lib/api";
import type {
  CyberCaseReport,
  EvidenceStatus,
  ReportWorkflowResponse,
  ReviewStatus,
  ReportType,
} from "@/lib/api";
import ReportMarkdownView from "@/components/report/ReportMarkdownView";

function statusClass(value: EvidenceStatus | ReviewStatus | string) {
  if (value === "confirmed" || value === "approved") {
    return "border-black bg-black text-white";
  }

  if (
    value === "reported" ||
    value === "reviewed" ||
    value === "ai_generated"
  ) {
    return "border-black/35 bg-white text-black";
  }

  if (value === "inferred") {
    return "border-black/15 bg-neutral-100 text-neutral-700";
  }

  return "border-black/15 bg-neutral-100 text-neutral";
}

function StatusBadge({
  value,
}: {
  value: EvidenceStatus | ReviewStatus | string;
}) {
  return (
    <span
      className={`inline-flex border px-2 py-1 text-[10px] font-black uppercase tracking-widest ${statusClass(
        value,
      )}`}
    >
      {value.replace("_", " ")}
    </span>
  );
}

function getHttpStatus(error: unknown): number | undefined {
  if (typeof error !== "object" || error === null || !("response" in error)) {
    return undefined;
  }

  const response = (error as { response?: { status?: number } }).response;
  return response?.status;
}



function ReportPreview({
  report,
  answer,
}: {
  report: CyberCaseReport | null;
  answer?: string;
}) {
  if (!report) return null;

  const title = report.title || "CyberCase Preliminary Incident Analysis Report";
  const reportDate = report.created_at?.slice(0, 10) || "Pending";

  return (
    <article className="mx-auto min-h-[760px] max-w-5xl border border-black/15 bg-white p-6 md:p-10">
      <div className="flex flex-col gap-5 border-b border-black pb-6 sm:flex-row sm:items-start sm:justify-between">
        <div>
          <p className="text-[10px] font-black uppercase tracking-widest text-neutral">
            CyberCase Investigation Report
          </p>

          <h2 className="mt-3 max-w-3xl text-3xl font-black leading-tight tracking-tight md:text-4xl text-black">
            {title}
          </h2>

          <div className="mt-5 flex flex-wrap gap-x-5 gap-y-2 text-[10px] font-black uppercase tracking-widest text-neutral">
            <span>Date: {reportDate}</span>
            <span>Generated by: CyberCase AI</span>
            <span>
              Classification:{" "}
              <span className="bg-black px-1.5 py-0.5 text-white">
                Internal
              </span>
            </span>
          </div>
        </div>

        <StatusBadge value={report.review_status || "draft"} />
      </div>

      <div className="mt-7">
        <ReportMarkdownView content={answer || ""} />
      </div>
    </article>
  );
}

export default function CaseReportWorkspace() {
  const params = useParams();
  const caseId = getRouteParam(params.caseId);
  const caseQuery = useCase(caseId);

  const [workflow, setWorkflow] = useState<ReportWorkflowResponse | null>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [isGenerating, setIsGenerating] = useState(false);
  const [isUpdatingStatus, setIsUpdatingStatus] = useState(false);
  const [isExporting, setIsExporting] = useState<"md" | "pdf" | null>(null);
  const [followupAnswer, setFollowupAnswer] = useState("");
  const [reportType, setReportType] = useState<ReportType>("overview");
  const [legal, setLegal] = useState(false);
  const [error, setError] = useState("");

  async function handleDownloadReport(format: "md" | "pdf") {
    if (!workflow || workflow.status !== "completed" || !workflow.report_id) return;
    setIsExporting(format);
    setError("");
    try {
      const blob = await downloadReportExport(workflow.report_id, format);
      const url = URL.createObjectURL(blob);
      const link = document.createElement("a");
      link.href = url;
      link.download = `cybercase-report-${workflow.report_id}.${format}`;
      document.body.appendChild(link);
      link.click();
      link.remove();
      URL.revokeObjectURL(url);
    } catch (err: unknown) {
      console.error(`Failed to export report in format ${format}:`, err);
      setError(`Failed to export report as ${format.toUpperCase()}.`);
    } finally {
      setIsExporting(null);
    }
  }

  useEffect(() => {
    if (!caseId) return;
    const activeCaseId = caseId;

    async function loadLatestReport() {
      setIsLoading(true);
      setError("");
      try {
        const data = await getLatestCaseReport(activeCaseId);
        setWorkflow(data);
      } catch (err: unknown) {
        // If 404, it means no report has been generated yet, which is expected
        if (getHttpStatus(err) !== 404) {
          console.error("Failed to load case report:", err);
          setError("Could not retrieve existing case report.");
        }
      } finally {
        setIsLoading(false);
      }
    }
    loadLatestReport();
  }, [caseId]);

  async function handleGenerate(force: boolean = false) {
    if (!caseId) return;

    setIsGenerating(true);
    setError("");
    try {
      const result = await generateCaseReport(caseId, reportType, legal, force);
      setWorkflow(result);
    } catch (err: unknown) {
      console.error("Failed to generate case report:", err);
      setError("Failed to generate report. Make sure database and RAG systems are operational.");
    } finally {
      setIsGenerating(false);
    }
  }

  async function handleResume() {
    if (!caseId || workflow?.status !== "followup" || !workflow.session_id) return;

    setIsGenerating(true);
    setError("");
    try {
      const result = await resumeCaseReport(caseId, workflow.session_id, followupAnswer.trim());
      setWorkflow(result);
      setFollowupAnswer("");
    } catch (err: unknown) {
      console.error("Failed to resume report generation:", err);
      setError("Could not submit follow-up response.");
    } finally {
      setIsGenerating(false);
    }
  }

  async function handleReviewStatusChange(status: ReviewStatus) {
    if (!workflow || workflow.status !== "completed" || !workflow.report_id) return;

    setIsUpdatingStatus(true);
    setError("");
    try {
      const result = await updateReportReviewStatus(workflow.report_id, status);
      setWorkflow(result);
    } catch (err) {
      console.error("Failed to update review status:", err);
      setError("Could not update review status.");
    } finally {
      setIsUpdatingStatus(false);
    }
  }

  if (!caseId) {
    return <CaseRouteState title="Case Report" message="No case ID provided." />;
  }

  if (caseQuery.isLoading) {
    return <CaseRouteState title="Case Report" message={`Loading case ${caseId}...`} />;
  }

  if (!caseQuery.data) {
    return <CaseRouteState title="Case Report" message="Could not load this case." />;
  }

  const activeReport = workflow?.status === "completed" ? workflow.report : null;
  const activeCompleteness = activeReport
    ? (activeReport.case_information_completeness ?? activeReport.case_fact_pack?.completeness ?? null)
    : workflow?.status === "followup"
    ? workflow.completeness
    : null;

  return (
    <CaseStageShell activeStage="report" caseData={caseQuery.data}>
      <div className="bg-[#FAF9F6] min-h-[600px] p-6">
        {error && (
          <div className="mb-6 mx-auto max-w-5xl border border-red-200 bg-red-50 p-4 text-xs font-semibold text-red-800">
            {error}
          </div>
        )}

        {isLoading ? (
          <div className="flex flex-col items-center justify-center py-20">
            <div className="h-8 w-8 animate-spin rounded-full border-4 border-black border-t-transparent" />
            <p className="mt-4 text-xs font-black uppercase tracking-widest text-neutral">
              Retrieving Case Report...
            </p>
          </div>
        ) : isGenerating ? (
          <div className="flex flex-col items-center justify-center py-20">
            <div className="h-8 w-8 animate-spin rounded-full border-4 border-black border-t-transparent" />
            <p className="mt-4 text-xs font-black uppercase tracking-widest text-neutral">
              Orchestrating internal RAG retrieval and generating CyberCase report...
            </p>
          </div>
        ) : workflow?.status === "error" || workflow?.status === "context_expired" ? (
          <div className="mx-auto max-w-2xl border border-red-200 bg-white p-6 text-center">
            <h3 className="text-base font-black text-red-800">
              Report generation could not complete
            </h3>
            <p className="mt-3 text-sm leading-6 text-red-700">
              {workflow.message}
            </p>
          </div>
        ) : workflow?.status === "completed" && activeReport ? (
          <div className="mx-auto max-w-5xl space-y-6">
            {/* Header / Actions Bar */}
            <div className="border border-black/10 bg-white p-4 flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
              <div className="flex flex-col gap-1">
                <span className="text-[10px] font-black uppercase tracking-widest text-neutral-500">
                  Report ID: {activeReport.report_id}
                </span>
                <span className="text-xs text-neutral-800">
                  Linked to Case: <strong className="font-bold">{caseQuery.data.title}</strong>
                </span>
              </div>

              <div className="flex flex-wrap items-center gap-4">
                <div className="flex items-center gap-2">
                  <label htmlFor="review-status-select" className="text-xs font-bold text-neutral-700">
                    Review Status:
                  </label>
                  <select
                    id="review-status-select"
                    value={activeReport.review_status}
                    disabled={isUpdatingStatus}
                    onChange={(e) => handleReviewStatusChange(e.target.value as ReviewStatus)}
                    className="border border-black/15 bg-white px-2.5 py-1.5 text-xs font-semibold text-black focus:outline-none focus:border-black"
                  >
                    <option value="draft">Draft</option>
                    <option value="ai_generated">AI Generated</option>
                    <option value="reviewed">Reviewed</option>
                    <option value="approved">Approved</option>
                  </select>
                </div>

                <button
                  onClick={() => handleDownloadReport("md")}
                  disabled={isExporting !== null}
                  className="border border-black bg-white px-4 py-1.5 text-xs font-black text-black hover:bg-neutral-50 disabled:opacity-40 transition"
                >
                  {isExporting === "md" ? "Exporting..." : "Download Markdown"}
                </button>

                <button
                  onClick={() => handleDownloadReport("pdf")}
                  disabled={isExporting !== null}
                  className="border border-black bg-white px-4 py-1.5 text-xs font-black text-black hover:bg-neutral-50 disabled:opacity-40 transition"
                >
                  {isExporting === "pdf" ? "Exporting..." : "Download PDF"}
                </button>

                <button
                  onClick={() => handleGenerate(true)}
                  className="border border-black bg-black px-4 py-1.5 text-xs font-black text-white hover:bg-neutral-800 transition"
                >
                  Regenerate
                </button>
              </div>
            </div>

            {/* Preview */}
            <ReportPreview
              report={activeReport}
              answer={workflow.status === "completed" ? workflow.answer : undefined}
            />
          </div>
        ) : workflow?.status === "followup" && workflow.session_id ? (
          <div className="mx-auto max-w-2xl border border-black/10 bg-white p-6 md:p-8">
            <span className="text-[10px] font-black uppercase tracking-widest text-neutral-500">
              Case Analysis Incomplete ({activeCompleteness?.percentage || 0}% Complete)
            </span>
            
            <h3 className="mt-3 text-lg font-black text-black">
              Incident Details Verification
            </h3>

            <p className="mt-2 text-sm text-neutral-700 leading-relaxed">
              Before the CyberCase investigation report can be finalized, additional details are recommended to improve MITRE technique mappings and legal assessment confidence.
            </p>

            <div className="mt-6 border border-black/10 bg-neutral-50 p-4">
              <p className="text-xs font-bold text-neutral-500 uppercase tracking-wide">
                Question from Case Assistant:
              </p>
              <p className="mt-1 text-sm font-semibold text-neutral-900">
                {workflow.followup_question}
              </p>
            </div>

            <div className="mt-6">
              <label htmlFor="followup-answer" className="text-xs font-bold text-neutral-700 uppercase tracking-wide block">
                Your Answer
              </label>
              <textarea
                id="followup-answer"
                rows={4}
                placeholder="Type your response here..."
                value={followupAnswer}
                onChange={(e) => setFollowupAnswer(e.target.value)}
                className="mt-2 w-full border border-black/15 px-3 py-2 text-xs bg-[#FAF9F6] text-black focus:outline-none focus:border-black"
              />
            </div>

            <div className="mt-6 flex flex-wrap gap-3 justify-end">
              <button
                onClick={() => handleGenerate(true)}
                className="border border-black/15 bg-white px-4 py-2 text-xs font-black text-black hover:border-black transition"
              >
                Skip & Force Generate
              </button>
              <button
                disabled={!followupAnswer.trim()}
                onClick={handleResume}
                className="border border-black bg-black px-4 py-2 text-xs font-black text-white hover:bg-neutral-800 disabled:opacity-40 transition"
              >
                Submit & Resume
              </button>
            </div>
          </div>
        ) : (
          <div className="mx-auto max-w-xl border border-black/10 bg-white p-8 text-center">
            <svg
              className="mx-auto h-12 w-12 text-neutral-400"
              fill="none"
              viewBox="0 0 24 24"
              stroke="currentColor"
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth={1}
                d="M9 17v-2m3 2v-4m3 4v-6m2 10H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"
              />
            </svg>

            <h3 className="mt-4 text-base font-black text-black">
              No Report Generated Yet
            </h3>
            
            <p className="mt-2 text-xs text-neutral-600 leading-relaxed">
              Generate an evidence-based cyber incident report for this case. This automatically analyzes incident details, maps threat techniques to MITRE ATT&CK, and assesses Thai cybersecurity law relevance.
            </p>

            <div className="mt-6 border-t border-black/10 pt-6 flex flex-col gap-4 text-left">
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label htmlFor="report-type-select" className="text-[10px] font-black uppercase tracking-wider text-neutral-500">
                    Report Type
                  </label>
                  <select
                    id="report-type-select"
                    value={reportType}
                    onChange={(e) => setReportType(e.target.value as ReportType)}
                    className="mt-1.5 w-full border border-black/15 bg-white px-2.5 py-1.5 text-xs font-semibold text-black focus:outline-none focus:border-black"
                  >
                    <option value="overview">Case Overview</option>
                    <option value="subject">Evidence & Indicators</option>
                    <option value="timeline">Incident Timeline</option>
                    <option value="vulnerability">Exposure & Risk</option>
                  </select>
                </div>

                <div className="flex flex-col justify-end pb-1">
                  <label htmlFor="legal-advice-checkbox" className="flex items-center gap-2 cursor-pointer select-none">
                    <input
                      id="legal-advice-checkbox"
                      type="checkbox"
                      checked={legal}
                      onChange={(e) => setLegal(e.target.checked)}
                      className="accent-black h-4 w-4"
                    />
                    <span className="text-xs font-semibold text-neutral-800">
                      Request Legal Assessment
                    </span>
                  </label>
                </div>
              </div>

              <button
                onClick={() => handleGenerate(false)}
                className="mt-4 border border-black bg-black py-2.5 text-xs font-black text-white hover:bg-neutral-800 transition"
              >
                Generate CyberCase Report
              </button>
            </div>
          </div>
        )}
      </div>
    </CaseStageShell>
  );
}
