import type { CaseAnalysisTrace } from "@/lib/api/types";

export const sourceMetrics: NonNullable<CaseAnalysisTrace["grounding"]> = {
  claims: 1,
  citations_claimed: 4,
  citations_verified: 3,
  citations_pointed: 0,
  citations_unfound: 1,
  claims_without_citation: 0,
  claims_duplicated: 0,
  citations_duplicated: 0,
  citations_marked: 0,
  citations_meaning_pointed: 0,
  evidence_ids_claimed: 4,
  evidence_ids_resolved: 3,
  evidence_ids_invalid: 1,
  evidence_id_resolution_rate: 0.75,
  claims_with_direct_evidence: 1,
  claims_with_recovered_evidence: 0,
  claims_without_resolved_evidence: 0,
  meaning_pointer_eligible: 0,
  meaning_pointer_attempted: 0,
  meaning_pointer_unavailable: 0,
  meaning_pointer_skipped: 0,
  associations_outside_context: 0,
  associations_without_claim: 0,
  summary_ids_unknown: 0,
  sources_cited: 1,
  sources_total: 1,
};
