from __future__ import annotations


B0_CANDIDATES = [
    {
        "name": "Qwen/Qwen2.5-1.5B-Instruct",
        "revision": "989aa7980e4cf806f80c7fef2b1adb7bc71aa306",
        "parameter_count": 1543714304,
        "parameter_count_human": "1.54B",
        "architecture": "Qwen2ForCausalLM",
        "context_length": 32768,
        "generation_length": 8192,
        "languages": "model card states more than 29 languages, including English and Chinese",
        "license": "Apache-2.0",
        "availability": "public Hugging Face safetensors; 3,087,467,144-byte checkpoint",
        "reproducibility": "pinned commit; Transformers model card path; no quantization",
        "cost_fairness": "recommended smallest modern general instruction baseline; larger and decoder-only versus mT5-base",
        "selected": True,
    },
    {
        "name": "Qwen/Qwen2.5-3B-Instruct",
        "revision": "aa8e72537993ba99e69dfaafa59ed015b17504d1",
        "parameter_count": 3085938688,
        "parameter_count_human": "3.09B",
        "architecture": "Qwen2ForCausalLM",
        "context_length": 32768,
        "generation_length": 8192,
        "languages": "model card states more than 29 languages, including English and Chinese",
        "license": "Qwen research/other tag in current repository metadata",
        "availability": "public Hugging Face safetensors; multi-shard checkpoint",
        "reproducibility": "pinned commit; Transformers model card path; no quantization",
        "cost_fairness": "stronger but materially less size-matched and less cleanly licensed for a baseline",
        "selected": False,
    },
    {
        "name": "Qwen/Qwen2.5-7B-Instruct",
        "revision": "a09a35458c702b33eeacc393d103063234e8bc28",
        "parameter_count": 7615616512,
        "parameter_count_human": "7.62B",
        "architecture": "Qwen2ForCausalLM",
        "context_length": 131072,
        "generation_length": 8192,
        "languages": "model card states more than 29 languages, including English and Chinese",
        "license": "Apache-2.0",
        "availability": "public Hugging Face safetensors; multi-shard checkpoint",
        "reproducibility": "pinned commit; Transformers model card path; no quantization",
        "cost_fairness": "capability ceiling candidate but substantially more memory and an unfairer size comparison",
        "selected": False,
    },
    {
        "name": "bigscience/mt0-base",
        "revision": "0c500042c1f80b6b6ec208cf73d9ee43f1dac245",
        "parameter_count": 582401280,
        "parameter_count_human": "0.58B",
        "architecture": "MT5ForConditionalGeneration",
        "context_length": "mT5-style relative attention; no serialized absolute maximum",
        "generation_length": "not pinned in this preflight",
        "languages": "model card lists 101 languages, including English and Chinese",
        "license": "Apache-2.0",
        "availability": "public Hugging Face safetensors; 2,329,638,768-byte checkpoint",
        "reproducibility": "pinned commit; same family and tokenizer class as B1",
        "cost_fairness": "best size and architecture control, but not a vanilla general-purpose causal instruction baseline",
        "selected": False,
    },
]


B0_RECOMMENDATION = {
    "name": "Qwen/Qwen2.5-1.5B-Instruct",
    "revision": "989aa7980e4cf806f80c7fef2b1adb7bc71aa306",
    "tokenizer_revision": "989aa7980e4cf806f80c7fef2b1adb7bc71aa306",
    "tokenizer_class": "Qwen2Tokenizer",
    "tokenizer_model_max_length": 131072,
    "parameter_count": 1543714304,
    "parameter_count_human": "1.54B",
    "architecture": "Qwen2ForCausalLM",
    "context_length": 32768,
    "generation_length": 8192,
    "config_max_position_embeddings": 32768,
    "checkpoint_dtype": "bfloat16",
    "license": "Apache-2.0",
    "precision": "float32, unquantized",
    "chat_template": "pinned repository tokenizer chat template with an empty system message, one user message, and add_generation_prompt=True",
    "selection_reason": "smallest candidate that is clearly a modern general instruction model, supports English and Chinese, has a public pinned checkpoint, and avoids the Qwen 3B repository license ambiguity",
}
