import ReportMarkdownView from "@/components/report/ReportMarkdownView";
import type { ReportCompletedResponse } from "@/lib/api";

export default function ReportPreview({ workflow }: { workflow: ReportCompletedResponse }) {
  const report = workflow.report;
  const title = report.title || "CyberCase Preliminary Investigation Report";
  const reportDate = report.created_at?.slice(0, 10) || "Pending";
  const manuallyEdited = workflow.edit_metadata.origin === "manual_edit";

  return (
    <article className="mx-auto min-h-[760px] max-w-5xl border border-black/15 bg-white p-6 md:p-10">
      <div className="flex flex-col gap-5 border-b border-black pb-6 sm:flex-row sm:items-start sm:justify-between">
        <div>
          <p className="text-[10px] font-black uppercase tracking-widest text-neutral">
            CyberCase Investigation Report
          </p>
          <h2 className="mt-3 max-w-3xl text-3xl font-black leading-tight tracking-tight text-black md:text-4xl">
            {title}
          </h2>
          <div className="mt-5 flex flex-wrap gap-x-5 gap-y-2 text-[10px] font-black uppercase tracking-widest text-neutral">
            <span>Date: {reportDate}</span>
            <span>{manuallyEdited ? "Generated report with analyst edits" : "Generated by CyberCase AI"}</span>
            <span>Classification: <span className="bg-black px-1.5 py-0.5 text-white">Internal</span></span>
          </div>
          {manuallyEdited ? (
            <p className="mt-3 text-xs font-semibold text-neutral-700">
              Analyst-edited fields: {workflow.edit_metadata.edited_fields.join(", ") || "narrative content"}
              {workflow.edit_metadata.edited_at
                ? ` at ${new Date(workflow.edit_metadata.edited_at).toLocaleString()}`
                : ""}.
            </p>
          ) : null}
        </div>
        <span className="inline-flex h-fit border border-black px-2 py-1 text-[10px] font-black uppercase tracking-widest">
          {report.review_status.replaceAll("_", " ")}
        </span>
      </div>
      <div className="mt-7">
        <ReportMarkdownView content={workflow.answer || ""} />
      </div>
    </article>
  );
}
