"use client";

import Link from "next/link";
import { useEffect, useState, useMemo } from "react";
import CyberCaseShell from "@/components/CyberCaseShell";
import {
  listReports,
  getReport,
  updateReportReviewStatus,
} from "@/lib/api";
import type {
  CyberCaseReport,
  EvidenceStatus,
  ReportWorkflowResponse,
  ReviewStatus,
  ReportRegistryItem,
} from "@/lib/api";

function statusClass(value: EvidenceStatus | ReviewStatus | string) {
  if (value === "confirmed" || value === "approved") {
    return "border-black bg-black text-white";
  }

  if (
    value === "reported" ||
    value === "reviewed" ||
    value === "ai_generated"
  ) {
    return "border-black/35 bg-white text-black";
  }

  if (value === "inferred") {
    return "border-black/15 bg-neutral-100 text-neutral-700";
  }

  return "border-black/15 bg-neutral-100 text-neutral";
}

function StatusBadge({
  value,
}: {
  value: EvidenceStatus | ReviewStatus | string;
}) {
  return (
    <span
      className={`inline-flex border px-2 py-1 text-[10px] font-black uppercase tracking-widest ${statusClass(
        value,
      )}`}
    >
      {value.replace("_", " ")}
    </span>
  );
}

function stripLeadingH1(markdown: string): string {
  return markdown.replace(/^\s*#\s+[^\n]*\n?/, "").trim();
}

function ReportPreview({
  report,
  answer,
}: {
  report: CyberCaseReport | null;
  answer?: string;
}) {
  if (!report) return null;

  const title = report.title || "CyberCase Preliminary Investigation Report";
  const reportDate = report.created_at?.slice(0, 10) || "Pending";

  return (
    <article className="mx-auto min-h-[760px] max-w-5xl border border-black/15 bg-white p-6 md:p-10">
      <div className="flex flex-col gap-5 border-b border-black pb-6 sm:flex-row sm:items-start sm:justify-between">
        <div>
          <p className="text-[10px] font-black uppercase tracking-widest text-neutral">
            CyberCase Investigation Report
          </p>

          <h2 className="mt-3 max-w-3xl text-3xl font-black leading-tight tracking-tight md:text-4xl text-black">
            {title}
          </h2>

          <div className="mt-5 flex flex-wrap gap-x-5 gap-y-2 text-[10px] font-black uppercase tracking-widest text-neutral">
            <span>Date: {reportDate}</span>
            <span>Generated by: CyberCase AI</span>
            <span>
              Classification:{" "}
              <span className="bg-black px-1.5 py-0.5 text-white">
                Internal
              </span>
            </span>
          </div>
        </div>

        <StatusBadge value={report.review_status || "draft"} />
      </div>

      <pre className="mt-7 whitespace-pre-wrap text-sm leading-7 text-neutral-800 font-sans">
        {answer ? stripLeadingH1(answer) : "No rendered report content is available."}
      </pre>
    </article>
  );
}

export default function ReportWorkspace() {
  const [reportsList, setReportsList] = useState<ReportRegistryItem[]>([]);
  const [selectedReportId, setSelectedReportId] = useState<string | null>(null);
  const [detailedWorkflow, setDetailedWorkflow] = useState<ReportWorkflowResponse | null>(null);
  const [searchQuery, setSearchQuery] = useState("");
  const [isLoadingList, setIsLoadingList] = useState(true);
  const [isLoadingDetail, setIsLoadingDetail] = useState(false);
  const [isUpdatingStatus, setIsUpdatingStatus] = useState(false);
  const [error, setError] = useState("");

  useEffect(() => {
    async function loadList() {
      setIsLoadingList(true);
      setError("");
      try {
        const data = await listReports();
        setReportsList(data);
      } catch (err) {
        console.error("Failed to load reports registry:", err);
        setError("Could not load reports registry from backend database.");
      } finally {
        setIsLoadingList(false);
      }
    }
    loadList();
  }, []);

  async function handleSelectReport(reportId: string) {
    setSelectedReportId(reportId);
    setIsLoadingDetail(true);
    setDetailedWorkflow(null);
    setError("");
    try {
      const data = await getReport(reportId);
      setDetailedWorkflow(data);
    } catch (err) {
      console.error("Failed to load report details:", err);
      setError("Could not load full report details.");
    } finally {
      setIsLoadingDetail(false);
    }
  }

  async function handleReviewStatusChange(status: ReviewStatus) {
    if (!selectedReportId || !detailedWorkflow || detailedWorkflow.status !== "completed") return;

    setIsUpdatingStatus(true);
    setError("");
    try {
      const result = await updateReportReviewStatus(selectedReportId, status);
      setDetailedWorkflow(result);
      
      // Update status in local list without reloading everything
      setReportsList(prev => 
        prev.map(r => r.report_id === selectedReportId ? { ...r, review_status: status } : r)
      );
    } catch (err) {
      console.error("Failed to update review status:", err);
      setError("Could not update report review status.");
    } finally {
      setIsUpdatingStatus(false);
    }
  }

  const filteredReports = useMemo(() => {
    return reportsList.filter(r => 
      r.case_title.toLowerCase().includes(searchQuery.toLowerCase()) ||
      r.case_id.toLowerCase().includes(searchQuery.toLowerCase()) ||
      r.report_id.toLowerCase().includes(searchQuery.toLowerCase())
    );
  }, [reportsList, searchQuery]);

  const activeReport =
    detailedWorkflow?.status === "completed" && detailedWorkflow.report_id === selectedReportId
      ? detailedWorkflow.report
      : null;

  return (
    <CyberCaseShell
      activeNav="Reports"
      eyebrow="Threat Intelligence & Documentation"
      title="Incident Reports Library"
      subtitle="Registry of all persisted case investigation reports"
      actions={
        <Link
          href="/cases"
          className="border border-black/15 px-3 py-2 text-xs font-black transition hover:border-black hover:bg-black hover:text-white bg-white text-black"
        >
          Go to Cases
        </Link>
      }
    >
      <div className="flex h-full min-h-0 flex-col xl:flex-row bg-[#FAF9F6]">
        {/* Left Side: Report List Panel */}
        <aside className="shrink-0 overflow-y-auto border-b border-black/10 bg-[#F5F4F0] xl:w-[380px] xl:border-b-0 xl:border-r flex flex-col h-full">
          <div className="p-4 border-b border-black/10 bg-white">
            <label htmlFor="search" className="sr-only">Search Reports</label>
            <input
              id="search"
              type="text"
              placeholder="Search reports by title or ID..."
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              className="w-full border border-black/15 px-3 py-2 text-xs bg-[#FAF9F6] text-black focus:outline-none focus:border-black"
            />
          </div>

          <div className="flex-1 overflow-y-auto">
            {isLoadingList ? (
              <div className="p-8 text-center text-xs font-black uppercase tracking-widest text-neutral">
                Loading Registry...
              </div>
            ) : filteredReports.length === 0 ? (
              <div className="p-8 text-center text-xs text-neutral">
                No reports found.
              </div>
            ) : (
              <div className="divide-y divide-black/5">
                {filteredReports.map((item) => (
                  <button
                    key={item.report_id}
                    onClick={() => handleSelectReport(item.report_id)}
                    className={`w-full text-left p-4 transition-all duration-200 border-l-4 ${
                      selectedReportId === item.report_id
                        ? "border-black bg-white shadow-sm"
                        : "border-transparent hover:bg-white/50"
                    }`}
                  >
                    <div className="flex justify-between items-start gap-2">
                      <span className="text-[10px] font-black uppercase tracking-widest text-neutral-500">
                        {item.case_id}
                      </span>
                      <span className={`text-[8px] font-black uppercase tracking-widest px-1.5 py-0.5 border ${
                        item.severity === "high" || item.severity === "critical"
                          ? "border-red-500/30 bg-red-50 text-red-700"
                          : item.severity === "medium"
                          ? "border-amber-500/30 bg-amber-50 text-amber-700"
                          : "border-neutral-300 bg-neutral-50 text-neutral-700"
                      }`}>
                        {item.severity}
                      </span>
                    </div>

                    <h3 className="mt-1.5 text-sm font-black text-black leading-snug line-clamp-2">
                      {item.case_title}
                    </h3>

                    <p className="mt-2 text-xs text-neutral-600 line-clamp-2">
                      {item.executive_summary_preview}
                    </p>

                    <div className="mt-3.5 flex justify-between items-center text-[9px] font-bold uppercase tracking-wider text-neutral-500">
                      <span>{item.created_at.slice(0, 10)}</span>
                      <span className="border border-black/10 px-1 py-0.5 bg-neutral-100 text-[8px]">
                        {item.review_status}
                      </span>
                    </div>
                  </button>
                ))}
              </div>
            )}
          </div>
        </aside>

        {/* Right Side: Report Detail View */}
        <main className="flex-1 overflow-y-auto p-6 md:p-10 flex flex-col">
          {error && (
            <div className="mb-6 border border-red-200 bg-red-50 p-4 text-xs font-semibold text-red-800">
              {error}
            </div>
          )}

          {isLoadingDetail ? (
            <div className="flex-1 flex flex-col items-center justify-center py-20">
              <div className="h-8 w-8 animate-spin rounded-full border-4 border-black border-t-transparent" />
              <p className="mt-4 text-xs font-black uppercase tracking-widest text-neutral">
                Retrieving Investigation Report...
              </p>
            </div>
          ) : detailedWorkflow?.status === "error" ||
            detailedWorkflow?.status === "context_expired" ? (
            <div className="flex-1 flex flex-col items-center justify-center border border-red-200 bg-white p-12 text-center">
              <h2 className="text-lg font-black text-red-800">
                Report details unavailable
              </h2>
              <p className="mt-3 max-w-md text-sm leading-6 text-red-700">
                {detailedWorkflow.message}
              </p>
            </div>
          ) : activeReport ? (
            <div className="flex-1 flex flex-col gap-6">
              {/* Action and Review Status Bar */}
              <div className="border border-black/10 bg-white p-4 flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
                <div className="text-xs">
                  <span className="font-bold text-neutral-500">Persisted Report ID: </span>
                  <code className="bg-neutral-100 px-1 py-0.5 font-mono text-black font-semibold">
                    {activeReport.report_id}
                  </code>
                </div>

                <div className="flex items-center gap-3">
                  <label htmlFor="review-status" className="text-xs font-bold text-neutral-700">
                    Review Status:
                  </label>
                  <select
                    id="review-status"
                    value={activeReport.review_status}
                    disabled={isUpdatingStatus}
                    onChange={(e) => handleReviewStatusChange(e.target.value as ReviewStatus)}
                    className="border border-black/15 bg-white px-2.5 py-1.5 text-xs font-semibold text-black focus:outline-none focus:border-black"
                  >
                    <option value="draft">Draft</option>
                    <option value="ai_generated">AI Generated</option>
                    <option value="reviewed">Reviewed</option>
                    <option value="approved">Approved</option>
                  </select>
                </div>
              </div>

              {/* The Actual Report Preview */}
              <ReportPreview
                report={activeReport}
                answer={
                  detailedWorkflow?.status === "completed" && detailedWorkflow.report_id === selectedReportId
                    ? detailedWorkflow.answer
                    : undefined
                }
              />
            </div>
          ) : (
            <div className="flex-1 flex flex-col items-center justify-center border-2 border-dashed border-black/10 rounded p-12 text-center bg-white/50">
              <svg
                className="h-12 w-12 text-neutral-400"
                fill="none"
                viewBox="0 0 24 24"
                stroke="currentColor"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth={1}
                  d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"
                />
              </svg>
              <h2 className="mt-4 text-lg font-black text-black">Incident Reports Library</h2>
              <p className="mt-2 max-w-md text-xs leading-5 text-neutral-600">
                Select an incident report from the registry list on the left to examine detailed MITRE technique mappings, timeline events, evidence files, and legal assessments.
              </p>
            </div>
          )}
        </main>
      </div>
    </CyberCaseShell>
  );
}
